---
version: "2"
services:
  smokeping:
    image: davarski/smokeping
    container_name: smokepingrrd
    environment:
      - TZ=Europe/Sofia
    volumes:
      - ./config:/config
      - smokeping-data:/data
    ports:
      - 8888:80
    restart: unless-stopped

volumes:
  smokeping-data:
    driver: local
